### ISSUE TITLE
Fail to build Unbound on Ubuntu

### ISSUE THREAD

**Issue by sebsto** [noloader/Build-Scripts#4]
I am trying to build `gnutls` on Ubuntu and I receive an error whn building `unbound` dependency:

```
test OK
Creating root key from data.iana.org
/home/ubuntu/gnutls/Build-Scripts/unbound-1.8.3/.libs/unbound-anchor: error while loading shared libraries: libunbound.so.8: cannot open shared object file: No such file or directory
Failed to verify root.key
Failed to build Unbound
```

```
# uname -a
Linux ip-172-31-16-177 4.15.0-1033-aws #35-Ubuntu SMP Wed Feb 6 13:29:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by noloader** [comment]
This should clear the issue: [Commit b5f3f6c11554](https://github.com/noloader/Build-Scripts/commit/b5f3f6c11554).

**Comment by sebsto** [comment]
Well, maybe there were two issues here, but the error message says it can not find the `libunbound.so.8` file.  

```
/home/ubuntu/gnutls/Build-Scripts/unbound-1.8.3/.libs/unbound-anchor: error while loading shared libraries: libunbound.so.8: cannot open shared object file: No such file or directory
```

Still not working after having pulled the latest commit.
This should not be closed.

**Comment by sebsto** [comment]
https://github.com/noloader/Build-Scripts/commit/316d581cc83ddffe6dc8a623a3db4de362ffe2e9 does not solve the problem neither, the error message says it still looks for v8 

```
/home/ubuntu/gnutls/Build-Scripts/unbound-1.9.0/.libs/unbound-anchor: error while loading shared libraries: libunbound.so.8: cannot open shared object file: No such file or directory
```

**Comment by noloader** [comment]
Yeah, something went sideways on my check-in. The script I tested used the latest unbound with an `LD_LIBRARY_PATH`.

`LD_LIBRARY_PATH` is needed because some fucking genius thought it was a good idea to compile and link against a library, and then load the wrong library at runtime. That fucking genius should get a Darwin award. It is sad Linux still has not fixed the problem after 30 years or so. BSDs, OS X, Solaris and even Windows managed to fix it.

**Comment by sebsto** [comment]
:-) indeed ...

Works now - thanks for the super quick replies.
